name: Build Image
env:
  DOCKERHUB_LOGIN : ${{ secrets.DOCKERHUB_LOGIN }}
  DOCKERHUB_PASSWORD : ${{ secrets.DOCKERHUB_PASSWORD }}

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: 'Dockerfile'
          push: true
          tags: regulaforensics/idv-aspk-proxy:finger_latest
          cache-from: type=registry,ref=regulaforensics/idv-aspk-proxy:finger_latest
          cache-to: type=inline